=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.	
=end

#Steps:- 
	# List fibonacci numbers
	# Add if they are even
	# Return sum of even < 4000000

def problem_two
	first_num = 1 #Let first number be 1
	second_num = 1 #we need this to make 2nd num
	sum = 0
	while sum < 4000000
		first_num, second_num = second_num, first_num + second_num
		if first_num.even?	
			sum += first_num	
		end
	end
	sum
end

puts problem_two

#$ ruby problem_2.rb
	#4613732